### ISSUE TITLE
Images with black backgrounds aren't captured

### ISSUE THREAD

**Issue by robstolarz** [robstolarz/ohno#3]
While running `./ohnoify.py ./build/originals/media/tumblr_ohijfwwRZ81vbwf2ko1_1280.png -o /tmp --debug` with the comic from http://webcomicname.com/post/153907364344, this debug output is produced:

```
[(4, 702720)]
image had 1 rectangles.
of these, the closest was 1.4142135623730951 units from the bottom right
```

I'm on Arch Linux 5.0.7-vfio, with Python 3.7.3 and 2.7.16, OpenCV 4.1.0.

**Comment by robstolarz** [comment]
I was hoping the [weird threshold inversion code](https://github.com/robstolarz/ohno/blob/1af894ac1adffadf9e982b7efb1799da222fe4ed/ohnoify.py#L24-L32) would have fixed this, but it seems that's not the case. The debug output seems to be showing it considering the entire image to be one panel, but then `--debug` never triggers the automatic uninversion case, so we have no idea what it's *actually* doing. Committing a thing that will make testing easier...

**Comment by robstolarz** [comment]
Okay, now the debug output looks like 
```
[(4, 702720)]
image had 1 rectangles.
of these, the closest was 1.4142135623730951 units from the bottom right
(inverting didn't work, what if we try not inverting it?)
[(9, 141752), (7, 120375), (7, 102664), (8, 92964), (8, 60000), (7, 59520), (5, 19278), (4, 13816), (6, 9300), (6, 8145), (9, 7038), (6, 3660), (10, 2964), (4, 2958), (8, 2360), (6, 1872), (6, 1702), (10, 1344), (8, 1147), (5, 1060), (10, 760), (11, 575), (9, 550), (11, 546), (11, 475), (8, 418), (9, 400), (11, 399), (11, 399), (10, 399), (8, 380), (9, 375), (12, 374), (12, 360), (10, 357), (11, 352), (9, 342), (5, 340), (10, 330), (11, 320), (10, 320), (13, 315), (7, 294), (10, 285), (8, 256), (12, 238), (11, 195), (7, 195), (6, 170), (8, 81), (9, 72), (8, 56), (8, 24), (4, 8)]
image had 2 rectangles.
of these, the closest was 864.3893798514648 units from the bottom right
Traceback (most recent call last):
  File "./ohnoify.py", line 28, in ohnoify_tryboththresholds
    ohnoify(inpath, outpath, debug, cv2.THRESH_BINARY_INV)
  File "./ohnoify.py", line 97, in ohnoify
    raise NotEnoughPanelsError(f"this comic ({inpath}) has too few panels, aborting")
__main__.NotEnoughPanelsError: this comic (./build/originals/media/tumblr_ohijfwwRZ81vbwf2ko1_1280.png) has too few panels, aborting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ohnoify.py", line 109, in <module>
    ohnoify_tryboththresholds(args.infile, args.outpath, args.debug)
  File "./ohnoify.py", line 32, in ohnoify_tryboththresholds
    ohnoify(inpath, outpath, debug, cv2.THRESH_BINARY)
  File "./ohnoify.py", line 97, in ohnoify
    raise NotEnoughPanelsError(f"this comic ({inpath}) has too few panels, aborting")
__main__.NotEnoughPanelsError: this comic (./build/originals/media/tumblr_ohijfwwRZ81vbwf2ko1_1280.png) has too few panels, aborting
```
and this image
![2019-04-14-212831_1284x552_scrot](https://user-images.githubusercontent.com/3682844/56102633-4aba3e80-5efc-11e9-97f3-5d0e68ac6f96.png)

So I guess by now it's obvious the uninverted threshold code actually works, and that this issue is a dupe of #2.
